server:
  port: 8091

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-fail: payment-fail
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:paymentdb}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      apache:
        kafka: OFF